#FROM mcr.microsoft.com/dotnet/runtime:5.0
FROM mcr.microsoft.com/dotnet/sdk:3.1
 ENV NUGET_XMLDOC_MODE skip
WORKDIR /vsdbg
#FROM remotecontainer:latest
RUN apt-get update -y \
 #&& apt-get install -y --allow-unauthenticated  libc6-dev  libgdiplus libx11-dev \
 #&& rm -rf /var/lib/apt/lists/. \
 #&& apt-get install -y apt-transport-https \
 && apt-get install -y redis-tools \
 #&& apt-get install openssh-server sudo -y 
    && apt-get install -y --no-install-recommends \
        unzip \
    && rm -rf /var/lib/apt/lists/* \
    && curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /vsdbg 
 
#RUN useradd -rm -d /home/ubuntu -s /bin/bash -g root -G sudo -p admin scada
#RUN adduser -S -D -h /usr/app/src scada root
RUN useradd -ms /bin/bash -p admin scada
#RUN echo "root:Docker!" | chpasswd
WORKDIR /app
COPY . . 
RUN chmod +x DCP
RUN chmod +x dcp-entrypoint.sh 
USER scada
#WORKDIR /app
ENTRYPOINT ["./dcp-entrypoint.sh"]

